defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning

development:
  <<: *defaults
  database: project_development
  pool: 5

test:
  <<: *defaults
  database: project_test
  pool: 5

production:
  <<: *defaults
  database: project_production
  pool: 5
